export { default as UserRoute } from './user_route'
export { default as RoleRoute } from './role_route'
export { default as CategoryRoute } from './category_route'
export { default as ProductRoute } from './product_route'
export { default as AddressRoute } from './address_route'
export { default as PayRoute } from './pay_route'
